sudo: required
services:
  - docker

before_install:
  - docker build -t iviberberi/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true iviberberi/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstals
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-247221886776"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"
